### ISSUE TITLE
Basemap Style for tileserver-gl

### ISSUE THREAD

**Issue by geo-tech** [syncpoint/basemap.at#1]
Could you provide your modifications for using Basemap Style in tileserver-gl?

**Comment by geo-tech** [comment]
Thanks.
The corrected version of root.json works in vector view correct, when i rename my Fonts subfolder from "Arial Bold" to "Arial-Bold", "Arial Regular" to "Arial-Regular", etc.

But i miss housenumber labeling.

To get raster view work, i need to change in root.json:
from `"url": "/data/basemap.at.json"` to `"url": "mbtiles://Basemap_20190617.mbtiles"`
and `"glyphs": "/{fontstack}/{range}.pbf",` to `"glyphs": "{fontstack}/{range}.pbf",`
But the Style in Raster wont be really Basemap.at Style.

**Comment by ThomasHalwax** [comment]
Thanks for your feedback! I fixed
* path for fonts handles blanks
* duplicate layer names
* added required properties in order to display house numbers
![image](https://user-images.githubusercontent.com/38359572/68892713-e2e30500-0723-11ea-8b49-b2b70e5ab8f6.png)

**Comment by geo-tech** [comment]
Thank you, works fine with actually original vector basemap release.
